#!/bin/bash
# Install quick-agent aliases idempotently.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_PATH="$SCRIPT_DIR/quick-agent.sh"
MARKER_START="# quick-agent aliases start"
MARKER_END="# quick-agent aliases end"
LEGACY_MARKER="# quick-claude"

if [[ -n "${ZSH_VERSION:-}" ]] || [[ "${SHELL:-}" == */zsh ]]; then
    RC_FILE="$HOME/.zshrc"
else
    RC_FILE="$HOME/.bashrc"
fi

prompt_default() {
    local prompt="$1"
    local default="$2"
    local value
    read -r -p "$prompt [$default]: " value
    printf '%s' "${value:-$default}"
}

is_valid_alias() {
    [[ "$1" =~ ^[A-Za-z_][A-Za-z0-9_-]*$ ]]
}

remove_managed_blocks() {
    local file="$1"
    [[ -f "$file" ]] || return 0

    local tmp
    tmp="$(mktemp)"

    awk -v start="$MARKER_START" -v end="$MARKER_END" -v legacy="$LEGACY_MARKER" '
        $0 == start { skip=1; next }
        $0 == end { skip=0; next }
        $0 == legacy { legacy_skip=1; next }
        legacy_skip && $0 ~ /^alias .*quick-claude\.sh/ { legacy_skip=0; next }
        legacy_skip { legacy_skip=0 }
        !skip { print }
    ' "$file" > "$tmp"

    cp "$file" "$file.bak"
    mv "$tmp" "$file"
}

REPOS_DIR_DEFAULT="$HOME/repos"
if [[ -t 0 ]]; then
    REPOS_DIR_VALUE="$(prompt_default "Repos directory" "$REPOS_DIR_DEFAULT")"
else
    REPOS_DIR_VALUE="$REPOS_DIR_DEFAULT"
fi

# Always rewrite generated config so repeated installs converge on the latest answer.
cat > "$SCRIPT_DIR/.env" <<EOF_ENV
# Generated by quick-agent install.sh. Re-run install.sh to change these.

# Directory containing your repos
REPOS_DIR="$REPOS_DIR_VALUE"

# Agent used by the generic launcher alias.
DEFAULT_AGENT="pi"
EOF_ENV

mkdir -p "$(dirname "$RC_FILE")"
touch "$RC_FILE"
remove_managed_blocks "$RC_FILE"

declare -a alias_order=()
declare -A alias_commands=()

set_alias() {
    local chosen="$1"
    local command="$2"

    if ! is_valid_alias "$chosen"; then
        echo "Skipping invalid alias '$chosen'" >&2
        return 0
    fi

    # If the user reuses an alias later in the prompts, the later answer wins.
    if [[ -z "${alias_commands[$chosen]+x}" ]]; then
        alias_order+=("$chosen")
    fi
    alias_commands[$chosen]="$command"
}

add_alias_if_available() {
    local default_alias="$1"
    local agent_name="$2"
    local binary="$3"
    local command_arg="$4"

    if command -v "$binary" >/dev/null 2>&1; then
        local chosen="$default_alias"
        if [[ -t 0 ]]; then
            read -r -p "Alias for $agent_name ($(command -v "$binary")) [$default_alias, blank to skip]: " chosen
            # Enter = default; '-' or 'none' = explicit skip.
            chosen="${chosen:-$default_alias}"
        fi
        [[ "$chosen" == "-" || "$chosen" == "none" ]] && return 0
        set_alias "$chosen" "source $SCRIPT_PATH $command_arg"
    fi
}

# User-requested defaults:
#   w -> pi
#   c -> claude dangerous
#   s -> opencode
# plus notable agents when present.
add_alias_if_available "w" "pi" "pi" "pi"
add_alias_if_available "c" "Claude Code" "claude" "claude"
add_alias_if_available "s" "OpenCode" "opencode" "opencode"
add_alias_if_available "x" "Codex" "codex" "codex"
add_alias_if_available "g" "Gemini CLI" "gemini" "gemini"

# Fallback generic alias if no detected/default agent claimed w.
if [[ -z "${alias_commands[w]+x}" ]]; then
    set_alias "w" "source $SCRIPT_PATH"
fi

{
    echo ""
    echo "$MARKER_START"
    echo "# Generated by $SCRIPT_PATH on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Re-run install.sh to replace this whole block. Run uninstall.sh to remove it."
    for alias_name in "${alias_order[@]}"; do
        [[ -n "${alias_commands[$alias_name]+x}" ]] || continue
        printf "alias %s='%s'\n" "$alias_name" "${alias_commands[$alias_name]}"
    done
    echo "$MARKER_END"
} >> "$RC_FILE"

echo "Installed quick-agent in $RC_FILE"
echo "Config written to $SCRIPT_DIR/.env"
echo ""
echo "Aliases:"
for alias_name in "${alias_order[@]}"; do
    [[ -n "${alias_commands[$alias_name]+x}" ]] || continue
    printf "  alias %s='%s'\n" "$alias_name" "${alias_commands[$alias_name]}"
done
echo ""
echo "Run 'source $RC_FILE' or restart your shell."
